[build]
  publish = "build"
  command = "bundle exec middleman build"

[build.environment]
  RUBY_VERSION = "3.1.2"

# Redirects per gestire le pagine multilingua
[[redirects]]
  from = "/en"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/fr"
  to = "/fr/index.html"  
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/fr/*" 
  to = "/fr/index.html"
  status = 200

# Fallback per pagine non trovate
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers per ottimizzazione
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
